<a href="https://colab.research.google.com/github/AHakeemk/python-basic-programs/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
import numpy as np
print(np.random.rand(3,3))

[[0.12265166 0.44874945 0.04781238]
 [0.25151914 0.09024437 0.83466992]
 [0.34230753 0.26020872 0.23154146]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [11]:
import numpy as np
import random
m=[random.randrange(1,50,5)for i in range(16)]
arr=np.array(m)
narr=arr.reshape(4,4)
 
rarr=arr.reshape(2,8)
 
hm=np.hstack(rarr)
 
vm=np.vstack(rarr)
 
print("4×4 matrix:",narr)
print("2×8 matrix:",rarr)
print("2×8 horizontal stack:",hm)
print("vertical stack:",vm)

4×4 matrix: [[46 31  6 46]
 [36 31 41 16]
 [ 6 26 46 41]
 [26 21 36 16]]
2×8 matrix: [[46 31  6 46 36 31 41 16]
 [ 6 26 46 41 26 21 36 16]]
2×8 horizontal stack: [46 31  6 46 36 31 41 16  6 26 46 41 26 21 36 16]
vertical stack: [[46 31  6 46 36 31 41 16]
 [ 6 26 46 41 26 21 36 16]]
