<a href="https://colab.research.google.com/github/AHakeemk/python-basic-programs/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [ ]:
import numpy as np 
m=np.arange(9).reshape(3,3)
print(np.sum(m))

36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [ ]:
 import numpy as np 
m=np.arange(9).reshape(3,3)
print("column sum: ",np.sum(m,axis=0))
print("row sum: ",np.sum(m,axis=1))

column sum:  [ 9 12 15]
row sum:  [ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [ ]:
 import numpy as np 
m=np.arange(16).reshape(4,4)
print("min: ",np.min(m))
print("max: ",np.max(m))
print("mean: ",np.mean(m))

min:  0
max:  15
mean:  7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [ ]:
 import numpy as np 
m=np.arange(100).reshape(10,10)
print("7th row:",m[6])
print("4-8 rows:",m[3:7])
print("5,5:",m[5,5])
print("5th column:",m[:,4])
print("2-5 columms:",m[:,1:4])

7th row: [60 61 62 63 64 65 66 67 68 69]
4-8 rows: [[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
5,5: 55
5th column: [ 4 14 24 34 44 54 64 74 84 94]
2-5 columms: [[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]
