<a href="https://colab.research.google.com/github/AHakeemk/python-basic-programs/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [ ]:
from numpy import random
m1=random.randint(10, size=(3,3))
m2=random.randint(10, size=(3,3))
p=m1.dot(m2)
print("dot product: ",p)
print("transpose: ",p.transpose())

dot product:  [[ 25  21  36]
 [ 62  33 117]
 [ 41  27  54]]
transpose:  [[ 25  62  41]
 [ 21  33  27]
 [ 36 117  54]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [ ]:
import numpy as np 
arr=np.array([[55,25,15], [30,44,2], [11,45,77]])
d=np.linalg.det(arr)
print("determinant: ",d)

determinant:  137180.0000000001
