<a href="https://colab.research.google.com/github/AHakeemk/python-basic-programs/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [ ]:
import numpy as np
arr=np.arange(16).reshape(4,4)
print (arr)
narr1=np.array_split(arr,1)
print(narr1)
narr2=np.array_split(arr,4)
print (narr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [ ]:
from numpy import random
m=random.rand(3,3)
print(m)
c=np.ceil(m)
print("ceil: ",c)
f=np.floor(m)
print("floor: ",f)

[[0.85907393 0.59751088 0.57642886]
 [0.95008219 0.93690187 0.40526783]
 [0.38756775 0.70553803 0.83034206]]
ceil:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
floor:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [ ]:
from numpy import random
m=random.randint(10,size=(1,4))
print("random: ",m,"shape: " ,np.shape(m))
s=np.squeeze(m)
print("squeeze: ",s,"shape: ",np.shape(s))
e=np.expand_dims(m,axis=1)
print("expand: ",e,"shape: ",np.shape(e))

random:  [[3 3 6 9]] shape:  (1, 4)
squeeze:  [3 3 6 9] shape:  (4,)
expand:  [[[3 3 6 9]]] shape:  (1, 1, 4)
